language: node_js
node_js:
- '8'
branches:
  only:
  - master
env:
  global:
  - NODE_ENV=travis CXX=g++-4.8
  - CC_TEST_REPORTER_ID=b9f1e5e340ca5000578a5559429f9482f913e6b03f40af529582f676db828899
services:
- docker
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_success:
- docker build -f server-static/Dockerfile -t dymajo/waka:latest ./  
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"